project: default
name: argocd-appset
namespace: argocd
repo: https://github.com/adityasinghal26/argocd-charts
targetRevision: main
appsDirectoryPath: apps/*
automatedSync: false
server: https://kubernetes.default.svc