apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.appsName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.appsName }}
spec:
  generators:
  - git:
      repoURL: {{ .Values.repo }}
      revision: {{ .Values.targetRevision }}
      directories:
      - path: {{ .Values.appsDirectoryPath }}
  template:
    metadata:
      name: {{`'{{path.basename}}'`}}
      namespace: {{ .Values.namespace }}
      labels:
        app.kubernetes.io/name: {{`'{{path.basename}}'`}}
    spec:
      project: {{ .Values.appsProject }}
      source:
        path: {{ .Values.path }}
        repoURL: {{ .Values.repo }}
        targetRevision: {{ .Values.targetRevision }}
        helm:
          valueFiles:
          - {{ .Values.valuesFileName }}
      destination:
        namespace: argocd
        server: {{ .Values.server }}
      {{- if .Values.automatedSync }}
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
        - FailOnSharedResource=true
        - RespectIgnoreDifferences=true
        - Validate=true
      {{- end }}
      {{- if not .Values.automatedSync }}
      syncPolicy:
        syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
        - FailOnSharedResource=true
        - RespectIgnoreDifferences=true
        - Validate=true
      {{- end }}